// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJcIKjq-NGFpifpxxS1qeoP4Yn2-o4Jk',
    appId: '1:1087551187437:web:9521b46488c9d41aeb5fe4',
    messagingSenderId: '1087551187437',
    projectId: 'ramaf-database',
    authDomain: 'ramaf-database.firebaseapp.com',
    storageBucket: 'ramaf-database.firebasestorage.app',
    measurementId: 'G-8XMYS8NM51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOrtUNEBRVsXaUnE949ehv9ZRa6t68tI',
    appId: '1:1087551187437:android:0c4f7bdf07f6ddf4eb5fe4',
    messagingSenderId: '1087551187437',
    projectId: 'ramaf-database',
    storageBucket: 'ramaf-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8P9T5QBSKemhC9xMa8WgZ91Fkpig0oM',
    appId: '1:1087551187437:ios:509a900f3b4216edeb5fe4',
    messagingSenderId: '1087551187437',
    projectId: 'ramaf-database',
    storageBucket: 'ramaf-database.firebasestorage.app',
    iosBundleId: 'com.example.ramafWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8P9T5QBSKemhC9xMa8WgZ91Fkpig0oM',
    appId: '1:1087551187437:ios:509a900f3b4216edeb5fe4',
    messagingSenderId: '1087551187437',
    projectId: 'ramaf-database',
    storageBucket: 'ramaf-database.firebasestorage.app',
    iosBundleId: 'com.example.ramafWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJcIKjq-NGFpifpxxS1qeoP4Yn2-o4Jk',
    appId: '1:1087551187437:web:583d2d1574be7eceeb5fe4',
    messagingSenderId: '1087551187437',
    projectId: 'ramaf-database',
    authDomain: 'ramaf-database.firebaseapp.com',
    storageBucket: 'ramaf-database.firebasestorage.app',
    measurementId: 'G-488PN8Q98B',
  );
}
